export const LOGIN_API_REQUEST = "LOGIN_API_CALL";
export const LOGIN_SET_RESPONSE = "LOGIN_SET_RESPONSE";
export const LOGIN_STATUS = "LOGIN_STATUS";

export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_API_REQUEST = "REGISTER_API_REQUEST";
export const REGISTER_SET_RESPONSE = "REGISTER_SET_RESPONSE";
export const REGISTER_RESET_RESPONSE = "REGISTER_RESET_RESPONSE";
